// This file handles all database-related logic using SQLite.
//
// You are responsible for:
// 1) Creating the `papers` table
// 2) Implementing the database operations below
//
// Do NOT handle HTTP status codes here.
// Do NOT perform request validation here.
// This layer should only deal with database operations.

const Database = require("better-sqlite3");

// ------------------------------------------------------------
// Connect to SQLite database
// ------------------------------------------------------------
const db = new Database("./paper_management.db");
console.log("Opened SQLite database");

// ------------------------------------------------------------
// TODO: Create a table named `papers`
//
// The table schema must match the assignment handout exactly.
// You should execute a CREATE TABLE IF NOT EXISTS statement.
// ------------------------------------------------------------

db.prepare(`
  CREATE TABLE IF NOT EXISTS papers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      authors TEXT NOT NULL,
      published_in TEXT NOT NULL,
      year INTEGER NOT NULL CHECK (year > 1900),
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`).run();

// ------------------------------------------------------------
// Database operations
//
// These functions run synchronously and return their results directly.
// Let unexpected errors propagate to Express' global error handler
// (the provided errorHandler in middleware.js).
// ------------------------------------------------------------

const formatTimestamp = (ts) => {
  if (!ts) return ts;
  if (typeof ts === "string" && !ts.endsWith("Z")) {
    return ts.replace(" ", "T") + ".000Z";
  }
  return ts;
};

const formatTimestamps = (paper) => {
  if (!paper) return paper;
  return {
    ...paper,
    created_at: formatTimestamp(paper.created_at),
    updated_at: formatTimestamp(paper.updated_at),
  };
};

const dbOperations = {
  // ----------------------------------------------------------
  // createPaper
  //
  // Inserts a new paper into the database.
  //
  // Input:
  // - paper object with title, authors, published_in, year
  //
  // Output:
  // - the newly created paper (including id and timestamps)
  //
  // Hint:
  // - Prepare an INSERT statement and execute it with .run().
  // - Use lastInsertRowid to identify the new row.
  // - Return the complete paper, including fields generated by the database.
  // ----------------------------------------------------------
  createPaper: (paper) => {
    // TODO: implement
    const stmt = db.prepare(`
      INSERT INTO papers (title, authors, published_in, year)
      VALUES (?, ?, ?, ?)
    `);
    const info = stmt.run(paper.title, paper.authors, paper.published_in, paper.year);
    return dbOperations.getPaperById(info.lastInsertRowid);
  },

  // ----------------------------------------------------------
  // getAllPapers
  //
  // Retrieves all papers, optionally applying filters.
  //
  // Supported filters:
  // - year
  // - published_in (partial match, case-insensitive)
  // - limit
  // - offset
  //
  // Output:
  // - array of paper objects
  //
  // Hint:
  // - Build WHERE conditions and a matching parameter array for filters.
  // - Use LIMIT and OFFSET for pagination.
  // - Prepare the SELECT query and use .all(...) to retrieve all matching rows.
  // ----------------------------------------------------------
  getAllPapers: (filters = {}) => {
    // TODO: implement
    let query = "SELECT * FROM papers WHERE 1=1";
    const params = [];

    if (filters.year !== undefined) {
      query += " AND year = ?";
      params.push(filters.year);
    }

    if (filters.published_in !== undefined) {
      query += " AND published_in LIKE ?";
      params.push(`%${filters.published_in}%`);
    }

    query += " LIMIT ? OFFSET ?";
    const limit = filters.limit !== undefined ? filters.limit : 10;
    const offset = filters.offset !== undefined ? filters.offset : 0;
    params.push(limit, offset);

    const stmt = db.prepare(query);
    return stmt.all(...params).map(formatTimestamps);
  },

  // ----------------------------------------------------------
  // getPaperById
  //
  // Retrieves a single paper by ID.
  //
  // Input:
  // - id (number)
  //
  // Output:
  // - paper object if found
  // - null / undefined if not found
  //
  // Hint:
  // - Prepare the SELECT query and use .get(...) to retrieve one matching row.
  // ----------------------------------------------------------
  getPaperById: (id) => {
    // TODO: implement
    const stmt = db.prepare("SELECT * FROM papers WHERE id = ?");
    return formatTimestamps(stmt.get(id));
  },

  // ----------------------------------------------------------
  // updatePaper
  //
  // Updates an existing paper by ID.
  //
  // Input:
  // - id (number)
  // - paper object with updated fields
  //
  // Output:
  // - updated paper object if successful
  // - null / undefined if paper does not exist
  //
  // Hint:
  // - Use .run(...) to execute the UPDATE statement.
  // - Set updated_at to CURRENT_TIMESTAMP; leave created_at unchanged.
  // - After updating, retrieve the paper again by ID and return it.
  // ----------------------------------------------------------
  updatePaper: (id, paper) => {
    // TODO: implement
    const existing = dbOperations.getPaperById(id);
    if (!existing) {
      return null;
    }

    const stmt = db.prepare(`
      UPDATE papers
      SET title = ?, authors = ?, published_in = ?, year = ?, updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `);
    stmt.run(paper.title, paper.authors, paper.published_in, paper.year, id);
    return dbOperations.getPaperById(id);
  },

  // ----------------------------------------------------------
  // deletePaper
  //
  // Deletes a paper by ID.
  //
  // Input:
  // - id (number)
  //
  // Output:
  // - no return value needed
  //
  // Hint:
  // - Use .run(...) to execute the DELETE statement.
  // ----------------------------------------------------------
  deletePaper: (id) => {
    // TODO: implement
    const stmt = db.prepare("DELETE FROM papers WHERE id = ?");
    stmt.run(id);
  },
};

// ------------------------------------------------------------
// Exports
// ------------------------------------------------------------
module.exports = {
  db, // export the database instance (used by tests)
  ...dbOperations, // export all database functions
};
